### PR TITLE
update from SuperBuild

### LINKED ISSUE #200: update_VM cannot update VM 3.2
The issue is detailed in https://github.com/SyneRBI/SIRF-SuperBuild/pull/703 and relates to the fact that this repo has been transferred to https://github.com/SyneRBI/SIRF-SuperBuild/

The update_VM.sh that is present in the 3.2 VM will launch the UPDATE.sh from this repo and hence not update the VM.

### PR DESCRIPTION
**Pull request by paskino**
closes #200

### CODE REVIEW

**Review by KrisThielemans — COMMENTED** [review]
I really don't know if this does the trick. I cannot imagine, as it's still going to do the UPDATE.sh that you've just modified.

Also, an update will definitely fail without the `-s` switch.

I don't have the bandwidth to test this I'm afraid, which is why I thought we'd agree to just write a message with a recommendation. But if you can test it, and it works, I'm happy!

**Comment by paskino** [comment]
I tested this as in https://github.com/SyneRBI/SIRF-SuperBuild/pull/747

**Comment by KrisThielemans** [comment]
I strongly suggest to port some of this to the SIRf-SuperBuild repo, and in this repo just let `UPDATE.sh` error out with a message that tells users what to do. (i.e. update their local version of the SB, and execute its `UPDATE.sh -s`. Otherwise we will have to keep this repo up-to-date for the next one anyway.

However, in the SB, I'd rather keep the original `INSTALL*` files, and let those call the `docker` files. Reasons:
- I feel this allows us to do VirtualBox specific stuff. 
- the `INSTALL` scripts are used in https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/cloud/terraform/azure/packer/scripts/provision.sh
- they have logical names in my opinion :-)

**Comment by paskino** [comment]
Especially the file names in the docker directory aren't very clear!

**Comment by KrisThielemans** [comment]
Closing here as we won't keep the repo up-to-date. Ideas here are in
https://github.com/SyneRBI/SIRF-SuperBuild/pull/755 and https://github.com/SyneRBI/SIRF-SuperBuild/pull/758

**Pull request closed without merging**
