### PR TITLE
auto update self

### PR DESCRIPTION
**Pull request by casperdcl**
UPDATE.sh should be able to update itself

### CODE REVIEW

**Comment by casperdcl** [comment]
​
On 3 February 2017 at 11:11, <evgueni.ovtchinnikov@stfc.ac.uk> wrote:

    Hi Casper,

    I have just realized that the VM update script update_VM.sh first pulls CCPPETMR_VM repo - does the folder CCPPETMR_VM still need to be removed and cloned?

    If it does, then UPDATE.sh may not be able to do it because it runs from this folder - or may it?

    A quick (and ugly) fix for this I can think of is to have this at the top of UPDATE.sh:

    cd $SRC_PATH
    if [ -z $SCRIPT_OF_3FEB17 ]
    then
      echo "Please remove CCPPETMR_VM, git clone it and run update_VM.sh again"
      export $SCRIPT_OF_3FEB17=true
      echo 'export $SCRIPT_OF_3FEB17=true' >> ~/.bashrc
      exit
    fi

    This workaround, of course, would fail miserably should the user fail to follow the instructions.

    Can you think of a more elegant and reliable workaround?

    From: CCP-PETMR Developers list [CCP-PETMR-DEVEL@JISCMAIL.AC.UK] on behalf of Casper da Costa-Luis [imaging@CASPERSCI.UK.TO]
    Sent: Thursday, February 02, 2017 10:59 AM
    To: CCP-PETMR-DEVEL@JISCMAIL.AC.UK
    Subject: Re: CCPPETMR_VM

    Hi Evgueni,

    cloning VM repo: The VM repo doesn't have any submodules so the recursive option would be ignored.

    updating VM repo after my force-push: it's tiny so I'd recommend deleting it and `git clone` afresh.

    Regards,
    Casper

**Comment by casperdcl** [comment]
one caveat is that the update script will have to be run while in the CCPPETMR_VM directory (ie cd CCPPETMR_VM && ./UPDATE.sh)

**Comment by KrisThielemans** [comment]
we don't understand this i'm afraid.

this script is called (on the VM) from another one that first does a "git pull". So, the test on revisions will always be true, and so we will always do the "git reset --hard". That sounds dangerous to us.

Instead, it would have to check if the "git reset --hard" is necessary, and only then do this. We could maybe check for the data being in the history?

**Comment by KrisThielemans** [comment]
obsolete as we've decided not to try and cover the update in this case.

**Pull request closed without merging**
